### PR TITLE
feature/VL.ImGui.Stride BUGFIX and SceneWidget

### PR DESCRIPTION
**Pull request by kopffarben**
# PR Details

working SceneWidget

BUGFIX:
- compiler Error after fresh Cloning in ImGuiEffect.sdfx.cs
- VL.ImGui.Stride was not updated in VL when edit the source
  - problem was different TargetFramework in csproj (net8.0-windows) and vvvv\packs\VL.ImGui.Stride\lib (net8.0-windows7.0) so vl use allways version from vvvv-folder

### CODE REVIEW

**Comment by azeno** [comment]
Not sure about the two bugfix commits. Are you sure you were working on a clean state of the repo?
I just did a `git clean -xfd` on the main branch followed by a `dotnet build`. All good. I now opened it with VS, changed a few lines of code in the VL.ImGui.Stride project, set a breakpoint, started and breakpoint was hit on the new code line, so it did load the correct dll. Therefor I'll only merge your Scene widget part and keep the two "bugfixes" out of it.

**Comment by azeno** [comment]
Cherry picked the SceneWidget fix, kept out the other two. If your problem persists after a `git clean -xfd` + `dotnet build` we can follow up on it.

**Comment by kopffarben** [comment]
Have you tried this with the https://github.com/vvvv/VL.StandardLibs/ ... or with your internal solutution? 
I definitely need the ShaderBugfix here ... bugfix 

https://github.com/vvvv/VL.StandardLibs/pull/671/commits/09bf3cc765d96a72976b910893e4eaddd6185173

Sitting at the laptop ...
What I have done:
- StandardLibs completely new cloned 
- Started Visual Studio and started Debug all "Work on ImGui.Stride" 

Error CS0103 The name 'ImGuiEffectKeys' does not exist in the current context VL.ImGui.Stride D:\VL.StandardLibs\VL.ImGui.Stride\src\Effects\ImGuiEffect.sdfx.cs 25 Active

**Comment by kopffarben** [comment]
so for my part I seem to need this bugfix

**Comment by azeno** [comment]
I did test with VL.StandardLibs of course. Is it maybe about the Stride plugin? I believe I have it disabled. Let me check.

**Comment by azeno** [comment]
I have it installed and enabled. Makes no sense. Can you try a build from command line like I did?

**Comment by kopffarben** [comment]
I will try tomorrow ... I'm currently AFK 
But for all people how try to build with VS we should deliver a sln without an error

**Comment by azeno** [comment]
Just tested on another machine, all good.

**Comment by kopffarben** [comment]
i tested dotnet build on my machine ... same issue ... i think my machine need complete reinstall
THX

**Comment by azeno** [comment]
Guess what, after switching branch and building our internal solution:
grafik

**Comment by azeno** [comment]
It somehow has to do with the Stride plugin... in any case will fix it. Thanks
